sudo: required
services: 
  - docker

before_install:
  - docker build -t zingroo/docker-react-app -f Dockerfile.dev .

script:
  - docker run zingroo/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "My-docker-App"
  env: "MyDockerApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-439388943230"
  bucket_path: "My-docker-App"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

